---
all:
  vars:
    # Global variables for both accounts
    aws_region: "us-east-1"
    management_account_id: "741752824171"
    dev_account_id: "193779369106"
    external_id: "DiskMonitoring-CrossAccount-12345"
    cloudwatch_namespace: "DiskMonitoring"
    metrics_collection_interval: 60
    
  children:
    management_account:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
      vars:
        account_id: "741752824171"
        account_name: "management"
        account_role: "DiskMonitoringManagementRole"
        regions:
          - us-east-1
    
    member_accounts:
      children:
        account_dev:
          vars:
            account_id: "193779369106"
            account_name: "dev"
            account_role: "DiskMonitoringCrossAccountRole"
            regions:
              - us-east-1

    linux_instances:
      children:
        - management_account
        - account_dev
    
    windows_instances:
      children:
        - management_account
        - account_dev
